import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { MainLayout } from "./layouts/Main";

const montserratARM = localFont({
  src: [
    {
      path: "./fonts/Montserratarm-SemiBold.woff",
      weight: "600",
      style: "semibold",
    },
  ],
  variable: "--font-montserrat-arm",
});

export const metadata: Metadata = {
  title: "Հարսանյաց հրավիրատոմս",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={`${montserratARM.variable} antialiased`}>
        <MainLayout />
      </body>
    </html>
  );
}
